### ISSUE TITLE
TryCatchInject#beginTraverseFile方法有问题

### ISSUE THREAD

**Issue by EspoirX** [feelschaotic/AopAutoTryCatch#4]
这方法中有一句  
```
int index = filePath.indexOf(packageName.replace(".", File.separator))
```
packageName 在外面传进来的时候格式是  com\\feelschaotic\\javassist
所以里面没有包含 “.”  ,  这里 replace 的结果跟没 replace 是一样的

而 filePath 是路径大概是这样的：
```
app/build/intermediates/javac/debug/compileDebugJavaWithJavac/classes/com/feelschaotic/javassist
```

所以 index 的结果永远都是 -1 。下面 isClassFilePath 的判断永远都为 false。

所以我觉得这样改就可以了：
```
int index = filePath.indexOf(packageName.replace("\\", "/"))
```

**Comment by feelschaotic** [comment]
这里有几个问题，我依次回答下：

1. 为什么有`replace(".", File.separator)`？

   正是因为packageName是**外部传入**的，支持业务方传入自定义的目录，所以业务方可能会传入`com\feelschaotic\javassist`也可能`com.feelschaotic.javassist`。

2.  index 的结果永远都是 -1？

    因为我的是window环境，所以packageName传入是`com\feelschaotic\javassist`，filePath路径分隔符也是 \，你本机的filePath分隔符是 /，应该是linux环境吧，所以才会出现 index 的结果永远都是 -1。你给的解决方案 `int index = filePath.indexOf(packageName.replace("\\", "/"))` 在window上会有问题的。
（这个环境问题我周末解决下，把业务方传入的路径分割转为对应的环境分隔符）

**Comment by EspoirX** [comment]
好的，明白了

**Comment by feelschaotic** [comment]
commit 940dd77b809fe77c55c6dbd837948f7993c20635  已经修复该问题
